[package]
name = "watcher-protocol-program"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []

[dependencies]
solana-program = "2.3.0"
thiserror = "2"
groth16-solana = { git = "https://github.com/Lightprotocol/groth16-solana", rev = "43fee1a67e91c0df7bb4edad5ba87ae4602aa208" }

[dev-dependencies]
solana-program-test = "2.3.0"
solana-sdk = "2.3.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
